config/routes.rb
Rails.application.routes.draw do
  root 'projects#home'
  get 'session/new'
  get '/syncplay' => 'projects#syncPlay'
  resources :songs
  resources :projects
  resources :users
  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'
  get "createProject"=>'project#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
    def fetch_user
      @current_user = User.find_by( :id => session[:user_id] )
      session[:user_id] = nil unless @current_user
    end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find_by :id => params[:id]

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    # redirect_to projects_path

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :date, :user_id, :song_id)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :authenticate, :only => [:new]

  def new
  end

  def create
    user = User.find_by :email => params[:email]
   if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in"
    
      redirect_to user
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out"
    redirect_to users_path
  end

  private
    def authenticate
      redirect_to users_path if @current_user
      # redirect_to :back if @current_user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorise, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    redirect_to root_path
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @user = User.find_by :id => params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  @user = User.find_by :id => params[:id]

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


    def authorise
      # Unless someone is logged in, take every request back to the login page.
      flash[:error] = "You need to be logged in for that" unless @current_user.present?
      redirect_to root_path unless @current_user.present?
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Music Maker</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Music Maker</a>
                </div>
                <div class="" id="navbar">
                    <ul class="nav navbar-nav pull-right">
                        <li><%= link_to "Home", root_path %></li>
                        <% if @current_user %>
                        <li><%= link_to "Profile", user_path(@current_user) %></li>
                        <li><%= link_to "Create Project", new_project_path %></li>
                        <li><%= link_to "Create Song", new_song_path %></li>
                        <li><%= link_to "Play together", syncplay_path %></li>
                        <li><%= link_to "Log out", logout_path, :method => :delete %></li>
                    <% else %>
                        <li><%= link_to "Sign up", new_user_path %></li>
                        <li><%= link_to "Log in", login_path %></li>
                        <li><%= link_to "Play together", syncplay_path %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>

        <%= yield %>

    </body>
</html>

app/views/projects/_form.html.erb
<div class="row">
    <div class="col-xs-4">
        <%= form_for(@project) do |f| %>
        <% if @project.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@project.errors.count, "error") %>
                prohibited this project from being saved:</h2>

            <ul>
                <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <div class="field">
            <%= f.label :name %><br>
            <%= f.text_area :name %>
        </div>
        <div class="field">
            <%= f.label :description %><br>
            <%= f.text_area :description %>
        </div>
        <div class="field">
            <%= f.label :date %><br>
            <%= f.datetime_select :date %>
        </div>
        <div class="field">
            <%= f.label :user_id %><br>
            <%= f.number_field :user_id %>
        </div>
        <div class="field">
            <%= f.label :song_id %><br>
            <%= f.number_field :song_id %>
        </div>
        <div class="actions">
            <%= f.submit %>
        </div>
    </div>
</div>
<% end %>

app/views/projects/home.html.erb
<!doctype html>
<html>
    <head></head>

    <body class="body-bg">
        <div class="container">

            <div id="main"></div>
            <script id="appViewTemplate" type="html/template">
                <div id="keyboard" class="text-center"></div>
                <div id="recordButton"></div>
                <div id="noteView"></div>
            </script>

            <script id="recordButtonViewTemplate" type="html/template">
                <div class="row">
                    <div class="col-xs-12 text-center margin-top-24">
                        <button id="recordStart" class="btn btn-lg btn-primary">Start</button>
                        <button id="recordEnd" class="btn btn-lg btn-primary">Stop</button>
                        <button id="playSong" class="btn btn-lg btn-primary">Listen</button>
                        <button id="saveSong" class="btn btn-lg btn-primary">Save</button>
                    </div>
                </div>
            </script>

            <script id="songInputViewTemplate" type="html/template">
                <div class="row">
                    <div class="col-xs-24 text-center">
                        <div class="text-center margin-top">
                            <div class="key">c<br>
                                <span>a</span>
                            </div>
                            <div class="key">D<br>
                                <span>s</span>
                            </div>
                            <div class="key">E<br>
                                <span>d</span>
                            </div>
                            <div class="key">F<br>
                                <span>f</span>
                            </div>
                            <div class="key">G<br>
                                <span>g</span>
                            </div>
                            <div class="key">A<br>
                                <span>h</span>
                            </div>
                            <div class="key">B<br>
                                <span>j</span>
                            </div>
                            <div class="key">C<br>
                                <span>k</span>
                            </div>
                        </div>
                    </div>
                </div>
            </script>
            <!-- <canvas width=700 height=100></canvas> -->
        </div>
    </body>
</html>

app/views/projects/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3 col-xs-offset-4">
            <p id="notice"><%= notice %></p>
            <table class="table">
              <tr>

                <th>
                    <strong>Name:</strong>
                    <%= @project.name %>
                </th>

                <th>
                    <strong>Description:</strong>
                    <%= @project.description %>
                </th>

                <th>
                    <strong>Date:</strong>
                    <%= @project.date %>
                </th>

                <th>
                    <strong>User:</strong>
                    <%= @project.user_id %>
                </th>

                <th>
                    <strong>Song:</strong>
                    <%= @project.song_id %>
                </th>
                </tr>
                <tr>
                  <td></td>

                </tr>
            </table>
            <%= link_to 'Edit', edit_project_path(@project) %>
            |
            <%= link_to 'Back', projects_path %>
        </div>
    </div>
</div>

app/views/projects/syncPlay.html.erb
<!doctype html>
<html>
    <head></head>
    <body class="body-bg">
        <div class="container">
            <div id="main"></div>
            <script>
              $(function() {
                // Create a new client to connect to Faye
                // var client = new Faye.Client('http://localhost:9292/faye');
                // Subscribe to the public channel
                var public_subscription = window.client.subscribe('/messages/public', function(data) {
                  console.log(data)
                  var noteRef = {
                    65: 3,
                    83: 5,
                    68: 7,
                    70: 8,
                    71: 10,
                    72: 12,
                    74: 14,
                    75: 15,
                    76: 3
                  }
                  // if (Object.keys(noteRef)data.keyCode )
                  var pitch = noteRef[data.keyCode]
                  if (data && pitch !== undefined) {
                    playNote(0, pitch, 0.1)
                    var pitches='';
                    // debugger;
                    if (data) {
                      pitches+= data.keyCode;
                    }
                    var oneNote = $("<span /span>")
                    oneNote.text( pitches );
                    oneNote.appendTo( "#noteView2" );

                  }
                });

                // Handle form submissions and post messages to faye
                $(document).on("keydown", function(event){
                  // Publish the message to the public channel
                  client.publish('/messages/public', {
                    username: '<%= session[:username] %>',
                    keyCode: event.which
                  });
                  // Don't actually submit the form, otherwise the page will refresh.
                  return false;
                });
              });
            </script>

            <script id="appViewTemplate" type="html/template">
                <div id="keyboard" class="text-center"></div>
                <div id="recordButton"></div>
                <div id="noteView"></div>
                <div id="noteView2"></div>
            </script>

            <script id="recordButtonViewTemplate" type="html/template">
                <div class="row">
                    <div class="col-xs-12 text-center margin-top-24">
                        <button id="recordStart" class="btn btn-lg btn-primary">Start</button>
                        <button id="recordEnd" class="btn btn-lg btn-primary">Stop</button>
                        <button id="playSong" class="btn btn-lg btn-primary">Listen</button>
                        <button id="saveSong" class="btn btn-lg btn-primary">Save</button>
                    </div>
                </div>
            </script>

            <script id="songInputViewTemplate" type="html/template">
              <h1 style="background:white;border-radius:30%;height:70px;">Play together</h1>
                <div class="row">
                    <div class="col-xs-24 text-center">
                        <div class="text-center margin-top">
                            <div class="key">c<br>
                                <span>a</span>
                            </div>
                            <div class="key">D<br>
                                <span>s</span>
                            </div>
                            <div class="key">E<br>
                                <span>d</span>
                            </div>
                            <div class="key">F<br>
                                <span>f</span>
                            </div>
                            <div class="key">G<br>
                                <span>g</span>
                            </div>
                            <div class="key">A<br>
                                <span>h</span>
                            </div>
                            <div class="key">B<br>
                                <span>j</span>
                            </div>
                            <div class="key">C<br>
                                <span>k</span>
                            </div>
                        </div>
                    </div>
                </div>
            </script>
            <!-- <canvas width=700 height=100></canvas> -->
        </div>
    </body>
</html>

app/views/session/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <h2>Login</h2>

            <%= form_tag login_path do %>
            <p>
                <%= label_tag :email %>
                <%= email_field_tag :email %>
            </p>

            <p>
                <%= label_tag :password %>
                <%= password_field_tag :password %>
            </p>

            <%= submit_tag "Login" %>
            <% end %>
        </div>
    </div>
</div>

app/views/songs/_form.html.erb
<div class="row">
    <div class="col-xs-4">
        <%= form_for(@song) do |f| %>
        <% if @song.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@song.errors.count, "error") %>
                prohibited this song from being saved:</h2>

            <ul>
                <% @song.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <div class="field">
            <%= f.label :name %><br>
            <%= f.text_area :name %>
        </div>
        <div class="field">
            <%= f.label :date %><br>
            <%= f.datetime_select :date %>
        </div>
        <div class="field">
            <%= f.label :project_id %><br>
            <%= f.number_field :project_id %>
        </div>
        <div class="field">
            <%= f.label :song_notes %><br>
            <%= f.text_area :song_notes %>
        </div>
        <div class="actions">
            <%= f.submit %>
        </div>
    </div>
</div>
<% end %>

app/views/songs/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3 col-xs-offset-4">
            <p id="notice"><%= notice %></p>

            <p>
                <strong>Name:</strong>
                <%= @song.name %>
            </p>

            <p>
                <strong>Date:</strong>
                <%= @song.date %>
            </p>

            <p>
                <strong>Project:</strong>
                <%= @song.project_id %>
            </p>

            <p>
                <strong>Song notes:</strong>
                <%= @song.song_notes %>
            </p>
        </div>
    </div>
</div>

<%= link_to 'Edit', edit_song_path(@song) %>
|
<%= link_to 'Back', songs_path %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-xs-12">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
<h3>New User</h3>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>
</div></div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <p id="notice"><%= notice %></p>
            <h1>Hello
                <%= @user.name %>!</h1>
            <!-- <p>
  <strong>Image:</strong>
  <%= @user.image %>
</p> -->

            <p>
                <strong>Name:</strong>
                <%= @user.name %>
            </p>

            <p>
                <strong>Email:</strong>
                <%= @user.email %>
            </p>
            <p>
            <%= link_to 'Edit', edit_user_path(@user) %>
            |
            <%= link_to 'Back', users_path %>
          </p>
        </div>
    </div>
</div>